recovery_behavior_enabled: true
clearing_rotation_allowed: true

controller_frequency: 10.0

TrajectoryPlannerROS:
   max_vel_x: 0.3
   min_vel_x: -0.3
   max_vel_y: 0.3
   min_vel_y: -0.3
   max_vel_theta: 0.5
   min_vel_theta: -0.5
   min_in_place_vel_theta: 0.2
   escape_vel: -0.3
   acc_lim_x: 1
   acc_lim_y: 1
   acc_lim_theta: 2
   holonomic_robot: true
   y_vels: [-0.2, -0.1, 0.1, 0.2]

   yaw_goal_tolerance: 0.2 # about 45.8 degrees
   xy_goal_tolerance: 0.2  # 40 cm
   latch_xy_goal_tolerance: true    ##

   meter_scoring: true

   pdist_scale: 1.4
   gdist_scale: 2.8

   heading_scoring: true            ##
   heading_lookahead: 0.5
   heading_scoring_timestep: 2.8    ##
   planner_patience: 5.0            
   oscillation_reset_dist: 0.05      
   publish_cost_grid_pc: false
   prune_plan: true

   controller_frequency: 10.0
   sim_time: 3.0
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 12
   vy_samples: 12
   vtheta_samples: 100
   dwa: true
   path_distance_bias: 32
   goal_distance_bias: 24
   occdist_scale: 0.01
   simple_attractor: false  
   # Debugging调试参数(debugging parameters)
   publish_traj_pc : true       # 将规划的轨迹在RVIZ上进行可视化(visualize the planned trajectory on RVIZ)
   publish_cost_grid_pc: true   # 将代价值进行可视化显示(visualize the cost)
   global_frame_id: slamware_map         # 全局参考坐标系(local reference coordinate system)
